version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Build and test
          command: |
            pwd
            ls -la
            npm install
      
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true

      - run:
          name: Task after Snyk
          command: |
            echo "Done"


